ARG BASE_IMAGE=icr.io/appcafe/websphere-liberty:full-java17-openj9-ubi

FROM $BASE_IMAGE AS websphere-liberty

COPY --chown=1001:0 ./target/guide-security-intro.war /config/apps/
COPY --chown=1001:0 ./src/main/liberty/config/server.xml /config/server.xml
COPY --chown=1001:0 ./src/main/liberty/config/userRegistry.xml /config/userRegistry.xml

# Setting for the verbose option
ARG VERBOSE=true
ARG FULL_IMAGE=true

# This script will add the requested XML snippets to enable Liberty features and grow image to be fit-for-purpose using featureUtility. 
# Only available in 'kernel-slim'. The 'full' tag already includes all features for convenience.

RUN if [ "$FULL_IMAGE" = "true" ] ; then echo "Skip running features.sh for full image" ; else features.sh ; fi

# This script will add the requested XML snippets and grow image to be fit-for-purpose
RUN configure.sh

